from pydantic import BaseModel
from typing import Literal
from common import SYSTEM_PROMPT


SUFFIX = "_hfhi"


RETRIEVAL_TOPICS = {
    "Housing in general": [
        "housing provision",
        "shelter provision",
        "housing construction",
        "shelter construction",
        "housing policy",
        "technical assistance for housing",
        "residential construction",
        "housing development",
        "urban housing",
        "rural housing",
        "inclusive housing",
        "housing access",
        "dwelling construction",
        "Smart housing ",
        "Public Private Partnerships (PPPs) for housing",
        "Capacity building for Housing, Land and Property (HLP)",
        "Legal advice for Housing, Land and Property (HLP)",
        "residential",
        "dwelling",
        "collective living quarters",
        "Green Housing",
        "residential dwelling energy efficiency",
        "carbon-neutral housing",
        "home energy use",
        "residential housing emissions"
    ],
    "Homelessness": [
        "homeless shelters",
        "homeless encampments",
        "tent cities",
        "tents for the homeless",
        "transitional housing for homeless",
        "unsheltered population",
        "temporary housing for homeless",
        "street homelessness",
        "permanent supportive housing",
        "housing first programs",
        "shelter programs for homeless",
        "Housing vouchers",
        "Dormitories",
        "Safe houses ",
        "Housing First",
        "statutory homeless",
        "chronic homelessness",
        "hidden homelessness",
        "indigenous homelessness",
        "sheltered homelessness",
        "unsheltered homelessness",
        "absolute homelessness",
        "relative homelessness",
        "accommodation for homeless people"
    ],
    "Transitional housing": [
        "emergency housing",
        "emergency shelters",
        "crisis housing",
        "disaster shelter",
        "disaster housing",
        "temporary shelter / housing",
        "refugee shelters",
        "humanitarian shelters",
        "temporary supportive housing",
        "emergency accommodation",
        "post-disaster housing",
        "shelters for displaced persons",
        "temporary accommodation for refugees",
        "Prefabricated housing",
        "Cash transfers for shelter",
        "Gender Based Violence (GBV) shelters ",
        "Youth Hostels ",
        "Co-living spaces ",
        "tents",
        "shelter kits",
        "non food items (Materials, tools and fixings)",
        "Short term rental support",
        "Transitional housing arrangements ",
        "Host family support",
        "habitability assessments",
        "Transitional shelter units",
        "accommodation for immigrants",
        "short-term leases",
        "long term recovery and reconstruction",
        "shelter for victims of abuse",
        "asylum claimant shelter",
        "single room occupancy",
        "rooming houses",
        "Cash transfers for housing",
        "Cash transfers for shelter",
        "shelter costs"
    ],
    "Incremental housing": [
        "housing improvement",
        "home repairs",
        "slum upgrading",
        "basic services for housing",
        "housing technical assistance",
        "incremental housing",
        "informal settlement upgrading",
        "water services for housing",
        "sanitation for housing",
        "energy services for housing",
        "upgrading informal housing",
        "Neighborhood upgrading",
        "Public space improvement",
        "Public space upgrading ",
        "community Facilities ",
        "Residential utilities",
        "Cadastral surveys",
        "Infrastructure improvement",
        "Progressive housing ",
        "provision of basic services",
        "housing condition improvements",
        "retrofits of buildings and infrastructure",
        "preservation",
        "repurpose housing",
        "Core housing",
        "Structural retrofit",
        "hazard risk reduction",
        "Waste management for housing",
        "regularization of housing/building",
        "legalization of  housing/building",
        "Land regularization",
        "Land titling",
        "formalization of housing/building",
        "formalization of land",
        "land incorporation ",
        "land readjustment ",
        "In-situ housing improvements",
        "land tenure ",
        "permanent repairs",
        "enumerations",
        "settlement planning",
        "redevelopment ",
        "resettlement",
        "relocation",
        "rehabitalization",
        "home expansion",
        "support for construction material suppliers",
        "materials and tools vouchers",
        "Construction skills training",
        "Community-level water and sanitation (WatSan) infrastructure ",
        "Street, roads and sidewalks",
        "Small drainage construction and repairs",
        "Construction technical assistance",
        "Legal advice for Housing, Land and Property (HLP) ",
        "sites and services",
        "plots",
        "urban integration",
        "infrastructure for housing developments",
        "transit oriented housing",
        "housing densification",
        "urban sprawl",
        "renovations",
        "structural need of repair",
        "plastic recycling for housing",
        "Agricultural waste recycling for housing ",
        "resilient housing",
        "nature based solutions for residential",
        "environmental protection for residential",
        "ecosystem restoration for residential",
        "adaptation of housing",
        "Eviction prevention, protection or moratorium",
        "aashwa'i",
        "ahata",
        "arrabal",
        "asentamiento",
        "barraca",
        "barrida",
        "barrio",
        "basti",
        "bidon",
        "bidonville",
        "brarek",
        "bustee",
        "campamento",
        "cantegril",
        "chawl",
        "chacarita",
        "ciudad perdida",
        "colonia popular",
        "comuna",
        "comunidade",
        "conventillos",
        "cortiço",
        "elendsviertel",
        "favela",
        "foundouks",
        "gecekondu",
        "ghetto",
        "illegal settlement",
        "imijondolo",
        "informal city/settlement",
        "habitat précaire",
        "habitat spontané",
        "hood",
        "jhopadpatti",
        "kampong",
        "kartonsko naselje",
        "katchi abadi",
        "katra",
        "kijiji",
        "lahbach",
        "loteamento",
        "mabanda",
        "masseque",
        "medina achouaia",
        "morro",
        "mudal safi",
        "pelli gewal",
        "poblacion callampa",
        "asentamiento precario",
        "pueblos jóvene",
        "quartier irrégulier",
        "quartos do slum",
        "shack",
        "shanty house / shanty town",
        "squatter city / camp / settlement",
        "tanake",
        "taudis",
        "truschobi",
        "tugurio",
        "umjondolo",
        "villa miseria",
        "watta"
    ],
    "Social housing": [
        "public housing",
        "affordable housing",
        "low-cost housing",
        "social housing",
        "nonprofit housing",
        "subsidized housing",
        "government-funded housing",
        "permanently affordable housing",
        "shared-equity housing",
        "municipal housing",
        "state-funded housing",
        "Rent vouchers",
        "Supply-side subsidies",
        "Demand-side subsidies",
        "Community Land Trust",
        "cooperative housing",
        "housing cooperatives",
        "Community-led housing",
        "Co-housing",
        "Housing associations",
        "Social rental agency",
        "Social rental",
        "Social-rental housing",
        "rental protection",
        "non-market housing",
        "Energy Service Company (ESCO)",
        "affordable rental",
        "social acceptability of housing projects (NIMBY)"
    ],
    "Market housing": [
        "home rental",
        "rental housing",
        "mortgages",
        "home financing",
        "rent-to-own housing",
        "market-rate housing",
        "private housing market",
        "real estate market",
        "homeownership programs",
        "property development",
        "private sector housing",
        "residential real estate",
        "housing investment",
        "landlord-tenant rental",
        "market rental",
        "market home ownership",
        "Housing Micro finance",
        "Micro Mortgages",
        "condominiums",
        "starter homes",
        "mortgage loan insurance",
        "mortgage securitization",
        "mortgage bonds",
        "tenant protection",
        "evictions",
        "forced moves",
        "foreign ownership",
        "speculation",
        "home flipping",
        "real estate fraud",
        "housing financialization",
        "mortgage debt",
        "housing investors",
        "residential development charges",
        "renovictions",
        "demovictions",
        "habitability",
        "construction productivity",
        "construction duration",
        "building technology",
        "modular building",
        "construction workers",
        "land use reforms",
        "building permitting",
        "zoning reform",
        "residential vacant land",
        "housing proximity to services, amenities and infrastructures",
        "housing mobility",
        "residential dwelling use",
        "crowding",
        "property rights",
        "suppressed households",
        "housing stability",
        "housing suitability",
        "housing stock",
        "housing needs",
        "building codes",
        "cultural adequacy",
        "dwelling adequacy",
        "housing accessibility",
        "subtenancy",
        "sublet dwellings",
        "Housing finance",
        "short-term rental",
        "low-cost financing",
        "Affordable housing finance",
        "subsidized loans",
        "affordable home loans"
    ]
}


DEFINITIONS = {
    "Housing in general": "explicitly describes activities related to the provision, development or policy of residential housing or shelter. It covers shelter and dwelling construction, urban and rural housing projects, and design of inclusive or collective living quarters. It includes technical assistance, capacity building, and legal advice on housing, land and property rights. It addresses policy frameworks, public-private partnerships, and smart, green or energy-efficient housing solutions. It also encompasses measures to improve housing access and reduce residential emissions through carbon-neutral design.",
    "Homelessness": "explicitly describes experiences, conditions, services or interventions related to people lacking stable housing. It includes unsheltered populations in tent cities, homeless encampments, street homelessness and hidden homelessness. It covers temporary and supportive accommodations for the unsheltered such as shelters, dormitories, safe houses and Housing First programs. It also encompasses permanent supportive housing, housing vouchers and other shelter and support programs. It addresses statutory, chronic, indigenous, sheltered, unsheltered, absolute and relative homelessness.",
    "Transitional housing": "explicitly describes the direct provision of temporary or emergency living quarters and related support for individuals or families displaced by crises, disasters, or other emergencies. To qualify, the activity must involve providing a physical shelter, not just support services. This includes emergency and crisis shelters, refugee and asylum seeker accommodation (excluding general camp management without a specific shelter provision component), and disaster relief shelters. It covers the distribution of shelter kits, tents, and essential non-food items for the express purpose of establishing immediate, temporary habitation. While it can include short-term rental support or host family placements, mentions of non-specific 'material relief,' 'support services,' or 'disaster preparedness' alone are insufficient.",
    "Incremental housing": "explicitly describes interventions that support gradual and participatory improvements to existing housing and related infrastructure in formal and informal contexts. It includes measures to provide or upgrade basic services, perform structural retrofits, preserve or repurpose dwellings and reduce hazard risks. It covers efforts to regularize, legalize and formalize housing, buildings and land through titling, readjustment and incorporation. It includes in-situ improvements, permanent repairs, enumeration, settlement planning, redevelopment, slum upgrading, relocation and resettlement. It also involves home expansion, core housing upgrades, rehabilitation and community infrastructure such as water, sanitation, drainage and transport networks. The subsector embraces support for construction material suppliers, tool and material vouchers, technical training and legal advice on housing, land and property rights. It addresses resilient and environmentally sound housing through nature-based solutions, ecosystem restoration, adaptation measures and recycling of plastic and agricultural waste. It includes eviction prevention and moratoriums and applies across diverse informal settlement types such as aashwa'i, barracas, bidonvilles, chawls, favelas, kampongs, slums, and villa miseria.",
    "Social housing": "explicitly describes housing programs or systems organized, funded, or managed by governments, nonprofits, or community groups to provide affordable or low-cost dwellings to low-income or vulnerable households. It covers the development, financing, allocation, and management of rental or ownership units with controlled or subsidized costs. It includes supply-side and demand-side subsidies, rent vouchers, permanently affordable models like shared-equity housing and community land trusts, and nonprofit or municipal housing schemes. It also encompasses cooperative housing, co-housing projects, social rental agencies, housing associations, and community-led initiatives. It addresses government-funded construction, rental protection measures, energy service company partnerships, and strategies to improve social acceptance of housing projects.",
    "Market housing": "explicitly describes housing supplied or financed through private market mechanisms. This includes rental housing and landlord-tenant relationships. It covers mortgages and home financing products such as conventional loans, micro-finance schemes, rent-to-own arrangements, mortgage securitization and insurance. It encompasses property development and residential real estate investment, including speculation, home flipping, foreign ownership and mortgage-backed securities. It involves construction and regulatory processes such as land use reforms, zoning, permitting, building technologies and modular construction. It addresses market dynamics such as market-rate rentals, homeownership programs, housing stock, affordability, evictions and tenant protection. It also covers financial instruments and policies such as mortgage bonds, development charges, low-cost and subsidized financing.",
    "Urban": "explicitly describes activities in specific urban locations",
    "Rural": "explicitly describes activities in specific rural locations"
}

# DEFINITIONS_V2 = {
#     "Housing in general": "explicitly describes activities related to the provision, development or policy of residential housing or shelter. It covers shelter and dwelling construction, urban and rural housing projects, and design of inclusive or collective living quarters. It includes technical assistance, capacity building, and legal advice on housing, land and property rights. It addresses policy frameworks, public-private partnerships, and smart, green or energy-efficient housing solutions. It also encompasses measures to improve housing access and reduce residential emissions through carbon-neutral design.",
#     "Homelessness": "explicitly describes experiences, conditions, services or interventions related to people lacking stable housing. It includes unsheltered populations in tent cities, homeless encampments, street homelessness and hidden homelessness. It covers temporary and supportive accommodations for the unsheltered such as shelters, dormitories, safe houses and Housing First programs. It also encompasses permanent supportive housing, housing vouchers and other shelter and support programs. It addresses statutory, chronic, indigenous, sheltered, unsheltered, absolute and relative homelessness.",
#     "Transitional housing": "explicitly describes the direct provision of temporary or emergency living quarters and related support for individuals or families displaced by crises, disasters, or other emergencies. To qualify, the activity must involve providing a physical shelter, not just support services. This includes emergency and crisis shelters, refugee and asylum seeker accommodation (excluding general camp management without a specific shelter provision component), and disaster relief shelters. It covers the distribution of shelter kits, tents, and essential non-food items for the express purpose of establishing immediate, temporary habitation. While it can include short-term rental support or host family placements, mentions of non-specific 'material relief,' 'support services,' or 'disaster preparedness' alone are insufficient.",
#     "Incremental housing": "explicitly describes interventions that support gradual and participatory improvements to existing housing and related infrastructure in formal and informal contexts. It includes measures to provide or upgrade basic services, perform structural retrofits, preserve or repurpose dwellings and reduce hazard risks. It covers efforts to regularize, legalize and formalize housing, buildings and land through titling, readjustment and incorporation. It includes in-situ improvements, permanent repairs, enumeration, settlement planning, redevelopment, slum upgrading, relocation and resettlement. It also involves home expansion, core housing upgrades, rehabilitation and community infrastructure such as water, sanitation, drainage and transport networks. The subsector embraces support for construction material suppliers, tool and material vouchers, technical training and legal advice on housing, land and property rights. It addresses resilient and environmentally sound housing through nature-based solutions, ecosystem restoration, adaptation measures and recycling of plastic and agricultural waste. It includes eviction prevention and moratoriums and applies across diverse informal settlement types such as aashwa'i, barracas, bidonvilles, chawls, favelas, kampongs, slums, and villa miseria.",
#     "Social housing": "explicitly describes housing programs or systems organized, funded, or managed by governments, nonprofits, or community groups to provide affordable or low-cost dwellings to low-income or vulnerable households. It covers the development, financing, allocation, and management of rental or ownership units with controlled or subsidized costs. It includes supply-side and demand-side subsidies, rent vouchers, permanently affordable models like shared-equity housing and community land trusts, and nonprofit or municipal housing schemes. It also encompasses cooperative housing, co-housing projects, social rental agencies, housing associations, and community-led initiatives. It addresses government-funded construction, rental protection measures, energy service company partnerships, and strategies to improve social acceptance of housing projects.",
#     "Market housing": "explicitly describes housing supplied or financed through private market mechanisms. This includes rental housing and landlord-tenant relationships. It covers mortgages and home financing products such as conventional loans, micro-finance schemes, rent-to-own arrangements, mortgage securitization and insurance. It encompasses property development and residential real estate investment, including speculation, home flipping, foreign ownership and mortgage-backed securities. It involves construction and regulatory processes such as land use reforms, zoning, permitting, building technologies and modular construction. It addresses market dynamics such as market-rate rentals, homeownership programs, housing stock, affordability, evictions and tenant protection. It also covers financial instruments and policies such as mortgage bonds, development charges, low-cost and subsidized financing.",
#     "Urban": "explicitly describes activities in specific urban locations",
#     "Rural": "explicitly describes activities in specific rural locations"
# }


# SYSTEM_PROMPT_V2 = SYSTEM_PROMPT.format(
#     "\n".join([f'- {key}' for key in DEFINITIONS_V2.keys()]),
#     "\n".join([f'- {key}: when the text {value}' for key, value in DEFINITIONS_V2.items()]),
# )


SYSTEM_PROMPT = SYSTEM_PROMPT.format(
    "\n".join([f'- {key}' for key in DEFINITIONS.keys()]),
    "\n".join([f'- {key}: when the text {value}' for key, value in DEFINITIONS.items()]),
)


class ReasonedClassification(BaseModel):
    summary: str
    reasoning: str
    classifications: list[Literal[tuple(DEFINITIONS.keys())]]


# class ReasonedClassificationV2(BaseModel):
#     summary: str
#     reasoning: str
#     classifications: list[Literal[tuple(DEFINITIONS_V2.keys())]]


if __name__ == '__main__':
    print(SYSTEM_PROMPT)
