from pydantic import BaseModel
from typing import Literal
from common import SYSTEM_PROMPT


SUFFIX = "_hfhi"


RETRIEVAL_TOPICS = {
    "Housing in general": [
        "housing provision",
        "shelter provision",
        "housing construction",
        "shelter construction",
        "housing policy",
        "technical assistance for housing",
        "residential construction",
        "housing development",
        "urban housing",
        "rural housing",
        "inclusive housing",
        "housing access",
        "dwelling construction",
        "Smart housing ",
        "Public Private Partnerships (PPPs) for housing",
        "Capacity building for Housing, Land and Property (HLP)",
        "Legal advice for Housing, Land and Property (HLP)",
        "residential",
        "dwelling",
        "collective living quarters",
        "Green Housing",
        "residential dwelling energy efficiency",
        "carbon-neutral housing",
        "home energy use",
        "residential housing emissions"
    ],
    "Homelessness": [
        "homeless shelters",
        "homeless encampments",
        "tent cities",
        "tents for the homeless",
        "transitional housing for homeless",
        "unsheltered population",
        "temporary housing for homeless",
        "street homelessness",
        "permanent supportive housing",
        "housing first programs",
        "shelter programs for homeless",
        "Housing vouchers",
        "Dormitories",
        "Safe houses ",
        "Housing First",
        "statutory homeless",
        "chronic homelessness",
        "hidden homelessness",
        "indigenous homelessness",
        "sheltered homelessness",
        "unsheltered homelessness",
        "absolute homelessness",
        "relative homelessness",
        "accommodation for homeless people"
    ],
    "Transitional housing": [
        "emergency housing",
        "emergency shelters",
        "crisis housing",
        "disaster shelter",
        "disaster housing",
        "temporary shelter / housing",
        "refugee shelters",
        "humanitarian shelters",
        "temporary supportive housing",
        "emergency accommodation",
        "post-disaster housing",
        "shelters for displaced persons",
        "temporary accommodation for refugees",
        "Prefabricated housing",
        "Cash transfers for shelter",
        "Gender Based Violence (GBV) shelters ",
        "Youth Hostels ",
        "Co-living spaces ",
        "tents",
        "shelter kits",
        "non food items (Materials, tools and fixings)",
        "Short term rental support",
        "Transitional housing arrangements ",
        "Host family support",
        "habitability assessments",
        "Transitional shelter units",
        "accommodation for immigrants",
        "short-term leases",
        "long term recovery and reconstruction",
        "shelter for victims of abuse",
        "asylum claimant shelter",
        "single room occupancy",
        "rooming houses",
        "Cash transfers for housing",
        "Cash transfers for shelter",
        "shelter costs"
    ],
    "Incremental housing": [
        "Progressive housing ",
        "provision of basic services",
        "housing condition improvements",
        "retrofits of buildings and infrastructure",
        "preservation",
        "repurpose housing",
        "Core housing",
        "Structural retrofit",
        "hazard risk reduction",
        "Waste management for housing",
        "regularization of housing/building",
        "legalization of  housing/building",
        "Land regularization",
        "Land titling",
        "formalization of housing/building",
        "formalization of land",
        "land incorporation ",
        "land readjustment ",
        "In-situ housing improvements",
        "land tenure ",
        "permanent repairs",
        "enumerations",
        "settlement planning",
        "redevelopment ",
        "resettlement",
        "relocation",
        "rehabitalization",
        "home expansion",
        "support for construction material suppliers",
        "materials and tools vouchers",
        "Construction skills training",
        "Community-level water and sanitation (WatSan) infrastructure ",
        "Street, roads and sidewalks",
        "Small drainage construction and repairs",
        "Construction technical assistance",
        "Legal advice for Housing, Land and Property (HLP) ",
        "sites and services",
        "plots",
        "urban integration",
        "infrastructure for housing developments",
        "transit oriented housing",
        "housing densification",
        "urban sprawl",
        "renovations",
        "structural need of repair",
        "plastic recycling for housing",
        "Agricultural waste recycling for housing ",
        "resilient housing",
        "nature based solutions for residential",
        "environmental protection for residential",
        "ecosystem restoration for residential",
        "adaptation of housing",
        "Eviction prevention, protection or moratorium",
        "aashwa'i",
        "ahata",
        "arrabal",
        "asentamiento",
        "barraca",
        "barrida",
        "barrio",
        "basti",
        "bidon",
        "bidonville",
        "brarek",
        "bustee",
        "campamento",
        "cantegril",
        "chawl",
        "chacarita",
        "ciudad perdida",
        "colonia popular",
        "comuna",
        "comunidade",
        "conventillos",
        "cortiço",
        "elendsviertel",
        "favela",
        "foundouks",
        "gecekondu",
        "ghetto",
        "illegal settlement",
        "imijondolo",
        "informal city/settlement",
        "habitat précaire",
        "habitat spontané",
        "hood",
        "jhopadpatti",
        "kampong",
        "kartonsko naselje",
        "katchi abadi",
        "katra",
        "kijiji",
        "lahbach",
        "loteamento",
        "mabanda",
        "masseque",
        "medina achouaia",
        "morro",
        "mudal safi",
        "pelli gewal",
        "poblacion callampa",
        "asentamiento precario",
        "pueblos jóvene",
        "quartier irrégulier",
        "quartos do slum",
        "shack",
        "shanty house / shanty town",
        "squatter city / camp / settlement",
        "tanake",
        "taudis",
        "truschobi",
        "tugurio",
        "umjondolo",
        "villa miseria",
        "watta"
    ],
    "Social housing": [
        "public housing",
        "affordable housing",
        "low-cost housing",
        "social housing",
        "nonprofit housing",
        "subsidized housing",
        "government-funded housing",
        "permanently affordable housing",
        "shared-equity housing",
        "municipal housing",
        "state-funded housing",
        "Rent vouchers",
        "Supply-side subsidies",
        "Demand-side subsidies",
        "Community Land Trust",
        "cooperative housing",
        "housing cooperatives",
        "Community-led housing",
        "Co-housing",
        "Housing associations",
        "Social rental agency",
        "Social rental",
        "Social-rental housing",
        "rental protection",
        "non-market housing",
        "Energy Service Company (ESCO)",
        "affordable rental",
        "social acceptability of housing projects (NIMBY)"
    ],
    "Market housing": [
        "home rental",
        "rental housing",
        "mortgages",
        "home financing",
        "rent-to-own housing",
        "market-rate housing",
        "private housing market",
        "real estate market",
        "homeownership programs",
        "property development",
        "private sector housing",
        "residential real estate",
        "housing investment",
        "landlord-tenant rental",
        "market rental",
        "market home ownership",
        "Housing Micro finance",
        "Micro Mortgages",
        "condominiums",
        "starter homes",
        "mortgage loan insurance",
        "mortgage securitization",
        "mortgage bonds",
        "tenant protection",
        "evictions",
        "forced moves",
        "foreign ownership",
        "speculation",
        "home flipping",
        "real estate fraud",
        "housing financialization",
        "mortgage debt",
        "housing investors",
        "residential development charges",
        "renovictions",
        "demovictions",
        "habitability",
        "construction productivity",
        "construction duration",
        "building technology",
        "modular building",
        "construction workers",
        "land use reforms",
        "building permitting",
        "zoning reform",
        "residential vacant land",
        "housing proximity to services, amenities and infrastructures",
        "housing mobility",
        "residential dwelling use",
        "crowding",
        "property rights",
        "suppressed households",
        "housing stability",
        "housing suitability",
        "housing stock",
        "housing needs",
        "building codes",
        "cultural adequacy",
        "dwelling adequacy",
        "housing accessibility",
        "subtenancy",
        "sublet dwellings",
        "Housing finance",
        "short-term rental",
        "low-cost financing",
        "Affordable housing finance",
        "subsidized loans",
        "affordable home loans"
    ]
}


DEFINITIONS = {
    "Housing general": "explicitly describes provision of housing/shelter, construction of housing/shelter (including eco-friendly building practices), housing policy, technical assistance for housing, or finance for housing",
    "Homelessness": "explicitly describes tents for the homeless, encampments for the homeless, or homeless shelters",
    "Transitional housing": "explicitly describes housing/shelter provided due to crises/disasters/emergencies, refugee shelters, refugee camps, or temporary supportive housing. The project must primarily involve the provision of housing or shelter; vague terms like 'material relief' alone are not sufficient evidence of housing provision. Mentions of refugees alone without additional housing/shelter context also do not qualify as Transitional housing",
    "Incremental housing": "explicitly describes housing sites, housing improvement/repairs, basic services for housing, or housing technical assistance. Basic services refer to water, sanitation, or energy improvements to housing. One important form of Incremental housing to look for is slum upgrading, but this class can be applied to any housing context",
    "Social housing": "explicitly describes Community Land Trusts (CLTs), cooperative housing, public housing, affordable housing, or low-cost housing. CLTs are defined as nonprofit organizations that acquire and hold land for the permanent benefit of the community",
    "Market housing": "explicitly describes home-rental, mortgages, rent-to-own housing, or market-rate housing",
    "Urban": "explicitly describes activities in specific urban locations",
    "Rural": "explicitly describes activities in specific rural locations"
}


SYSTEM_PROMPT = SYSTEM_PROMPT.format(
    "\n".join([f'- {key}' for key in DEFINITIONS.keys()]),
    "\n".join([f'- {key}: when the text {value}' for key, value in DEFINITIONS.items()]),
)


class ReasonedClassification(BaseModel):
    summary: str
    reasoning: str
    classifications: list[Literal[tuple(DEFINITIONS.keys())]]
